services:
  - type: web
    name: investment-backend
    env: python
    plan: free
    buildCommand: |
      pip cache purge
      pip install --upgrade pip
      pip install --upgrade "cython>=3.0.6"
      pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
